server:
  port: 8080
  error:
    whitelabel:
      enabled: false
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test02
    username: sa
    password: sapassword
  devtools:
    restart:
      poll-interval: 2s

  mail:
    host: smtp.gmail.com
    port: 587
    username: vutuankiet20022@gmail.com
    password: phvldanasccuicnt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true



